adding the books to the main page
Alzubair98/capstone-project-module-2 pull request #22
Opened 2022-07-25 22:00 UTC by Alzubair98

all the first requirement are done

1 - use API
2- add the books to the main page

2022-07-25 22:54 UTC, jaferIdrees requested changes
### Great job consuming the target API.
Highlights:

- The required data were retrieved correctly 👍 
- No linters errors 💯 

### Required changes:

- You need to implement basic styling as per the wire-frame
- Change the title to match your books query (e.g. Love books).

### Optional suggestions:
[OPTIONAL]: let the user change the books subject.

2022-07-25 22:54 UTC, jaferIdrees commented on src/consumeAPI.js
> +    const likeBtn = document.createElement('button');
It's recommended to keep declaration on the top of the block.

2022-07-25 22:54 UTC, jaferIdrees commented on src/consumeAPI.js
> +    image.src = `https://covers.openlibrary.org/b/id/${array[i].cover_id}-M.jpg`;
It's would be better to amend an alt text to each element (e.g. book title)

2022-07-25 23:08 UTC, jaferIdrees commented on src/consumeAPI.js
> +    image.src = `https://covers.openlibrary.org/b/id/${array[i].cover_id}-M.jpg`;
![image](https://user-images.githubusercontent.com/58269142/180889398-a7c6e18a-7923-446e-a885-671c47a24b4c.png)

This is the main requirement for your part

2022-07-26 07:51 UTC, Alzubair98 commented on src/consumeAPI.js
> +    image.src = `https://covers.openlibrary.org/b/id/${array[i].cover_id}-M.jpg`;
hi @jaferIdrees 
what is missing in my part? 
can you mention it 
thanks

2022-07-26 08:41 UTC, Alzubair98 commented on src/consumeAPI.js
> +    const likeBtn = document.createElement('button');
@jaferIdrees 
dear it may be recommended but its not necessary 
I'm doing it that way so i can organize each item by it self which mean  i create the item i give it some classes or set something to it then i move to the next item

2022-07-26 08:53 UTC, Alzubair98 commented on src/consumeAPI.js
> +    image.src = `https://covers.openlibrary.org/b/id/${array[i].cover_id}-M.jpg`;
@jaferIdrees  you can check it now

2022-07-26 10:50 UTC, jaferIdrees approved these changes
Good to go.
But please change the title to Love Books before merge ❤️

2022-07-26 14:28 UTC, merged